### ISSUE TITLE
客户端启动报错

### ISSUE THREAD

**Issue by chika0801** [JimmyHuang454/RRS#2]
系统WIN11，非管理员权限打开命令提示符运行程序，报错如下
```
Running at: C:\Users\***\RRS_Windows
Using config at: C:\Users\***\RRS_Windows/config.json
log level set to "info" means print info user need to know.
Unhandled exception:
SocketException: Failed to create server socket (OS Error: 在其上下文中，该请求的地址无效。
, errno = 10049), address = VPS的IP, port = 443
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1030)
<asynchronous suspension>
#1      TransportServer.bind (package:proxy/transport/server/base.dart:107)
<asynchronous suspension>
#2      JLSIn.bind (package:proxy/inbounds/jls.dart:153)
<asynchronous suspension>
#3      _buildInbounds (package:proxy/handler.dart:93)
<asynchronous suspension>
#4      buildInbounds (package:proxy/handler.dart:102)
<asynchronous suspension>

```

客户端配置如下
```json
{
  "config": {
    "log": {
      "level": "info"
    }
  },
  "outbounds": {
    "jls": {
      "protocol": "jls",
      "setting": {
        "address": "VPS的IP", // 地址必填
        "port": 443,
        "password": "1702215852282362099115850105202494216820", // 密码和随机数也要填对
        "random": "1702215852282362099115850105202494216820"
      }
    },
    "myTrojan": {
      "protocol": "trojan",
      "setting": {
        "address": "VPS的IP",
        "port": 443,
        "password": "1702215852282362099115850105202494216820"
      },
      "outStream": {
        "tls": {
          "enable": true
        }
      }
    }
  },
  "inbounds": {
    "HTTP": {
      "protocol": "http",
      "route": "proxy",
      "setting": {
        "address": "127.0.0.1",
        "port": 8183 // 默认这个HTTP端口，可自行更改
      }
    },
    "jls": {
      "protocol": "jls",
      "setting": {
        "address": "VPS的IP",
        "password": "1702215852282362099115850105202494216820",
        "random": "1702215852282362099115850105202494216820",
        "port": 443
      },
      "route": "freedom"
    }
  },
  "balance": {
    "default": {
      "outbound": [
        "jls"
      ]
    }
  },
  "routes": {
    "proxy": {
      "rules": [
        {
          "outbound": "freedom",
          "domain": [
            "regex:.*.cn"
          ],
          "ip": [
            "192.168.0.0/16"
          ]
        },
        {
          "balance": "default",
          "domain": [
            "google",
            "twitter",
            "wiki",
            "instagram",
            "facebook",
            "youtube",
            "github"
          ]
        },
        {
          "outbound": "freedom",
          "ip": [
            {
              "ipdb": "defaultCN",
              "type": "CN"
            }
          ],
          "cache": {
            "enable": true,
            "size": 2000
          }
        },
        {
          "balance": "default"
        }
      ]
    }
  }
}

```

**Comment by JimmyHuang454** [comment]
```json
  "inbounds": {
    "HTTP": {
      "protocol": "http",
      "route": "proxy",
      "setting": {
        "address": "127.0.0.1",
        "port": 8183 // 默认这个HTTP端口，可自行更改
      }
    },
    "jls": { // 本机删掉这个，会监听443
      "protocol": "jls",
      "setting": {
        "address": "VPS的IP",
        "password": "1702215852282362099115850105202494216820",
        "random": "1702215852282362099115850105202494216820",
        "port": 443
      },
      "route": "freedom"
    }
  },
```
如果你本机使用的话，可以不用这个inbounds里面的 jls，他同时也是Server的配置，实际上本机和VPS都是使用一个config.json。

解决方法：Windows的config.json 删掉inbounds里的jls

**Comment by chika0801** [comment]
```
    "jls": { // 本机删掉这个，会监听443
      "protocol": "jls",
      "setting": {
        "address": "VPS的IP",
        "password": "1702215852282362099115850105202494216820",
        "random": "1702215852282362099115850105202494216820",
        "port": 443
      },
```

谢谢帮助。删除上面的内容，windows客户端能启动了。
